# Generated by Django 2.1.1 on 2018-12-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='цена')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('min_age', models.PositiveSmallIntegerField(default=12, verbose_name='минимальный возраст')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория книг',
                'verbose_name_plural': 'категории книг',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interesting_authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='Биография')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='добавлена')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='рейтинг')),
                ('photo', models.ImageField(blank=True, upload_to='news', verbose_name='фотография')),
                ('active', models.BooleanField(default=False, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'ordering': ['-added', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Interesting_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='добавлена')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='рейтинг')),
                ('photo', models.ImageField(blank=True, upload_to='news', verbose_name='фотография')),
                ('active', models.BooleanField(default=False, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-added', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Published_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='добавлена')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='рейтинг')),
                ('photo', models.ImageField(blank=True, upload_to='news', verbose_name='фотография')),
                ('active', models.BooleanField(default=False, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'вышедшая книга',
                'verbose_name_plural': 'вышедшие книги',
                'ordering': ['-added', 'title'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.BookCategory', verbose_name='категория'),
        ),
    ]
