# Generated by Django 2.1.1 on 2019-05-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['category', 'title'], 'verbose_name': 'книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'ordering': ['name'], 'verbose_name': 'категория книг', 'verbose_name_plural': 'Категории книг'},
        ),
        migrations.AlterModelOptions(
            name='interesting_authors',
            options={'ordering': ['-added', 'title'], 'verbose_name': 'автор', 'verbose_name_plural': 'Топ_авторы'},
        ),
        migrations.AlterModelOptions(
            name='interesting_books',
            options={'ordering': ['-added', 'title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Топ_Книги'},
        ),
        migrations.AlterModelOptions(
            name='published_books',
            options={'ordering': ['-added', 'title'], 'verbose_name': 'вышедшая книга', 'verbose_name_plural': 'Вышедшие книги'},
        ),
    ]
